delete from athlete;
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('10', 'Caroline Bach', 'Mindested', 2005, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('11', 'Caroline Buhl', 'Schrøder', 2003, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('20', 'Frederik', 'Gersby', 2006, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('31', 'Julie', 'Stampe', 2002, 'WOMAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('35', 'Julie Krog', 'Rose', 2003, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('36', 'Karen', 'Markussen', 2007, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('42', 'Linea Funk', 'Larsen', 2007, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('46', 'Magnus', 'Løfquist', 2005, 'MAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('50', 'Malte Funk', 'Larsen', 2005, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('53', 'Mathilde Friis', 'Autzen', 2005, 'WOMAN', 'TRI');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('63', 'Sebastian Sand', 'Gottlieb', 2005, 'MAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('66', 'Theodor', 'Løvgreen', 2005, 'MAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('73', 'Andrea Lindberg', 'Vedøe', 2006, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('75', 'Noah', 'Anker-Møller', 2007, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('77', 'Johannes', 'Framke', 2006, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('78', 'Anne-Maj', 'Framke', 2008, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('79', 'Agnete', 'Boelt', 2006, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('81', 'Lucas Emil ', 'Christensen', 2003, 'MAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('82', 'Lucas', 'Linderoth', 2007, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('91', 'Laura Bach', 'Mindested', 2008, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('92', 'Simone Sofie', 'Stenberg', 2008, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('96', 'Laura', 'Weng', 2006, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('97', 'Astrid', 'Mulipola', 2006, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('99', 'Josephine ', 'Kruse', 2002, 'WOMAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('100', 'Magnus', 'Andersen', 1995, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('106', 'Lucas S.', 'Korger', 2007, 'MAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('107', 'Emma Them', 'Kjølholm', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('108', 'Liv Tjørnhøj', 'Rosenkrantz', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('110', 'Kajsa Marie', 'Andkjær', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('112', 'André ', 'Goldberg', 1999, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('113', 'Marie Katrine', 'Moesgaard', 2008, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('115', 'Liv', 'Rosenkrantz', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('116', 'Alma Lanng', 'Geneser', 2008, 'WOMAN', 'TRI');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('117', 'Katharina', 'Nekhonrochko', 2000, 'WOMAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('119', 'Aksel', 'Danielsen', 2009, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('120', 'Alex ', 'Doyle', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('121', 'Andreas ', 'Stengade Birck', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('122', 'Anja', 'Englert', 2008, 'WOMAN', 'S3');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('123', 'Axel', 'Bonke Jensen', 2009, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('124', 'Bertram', 'Garde Slothuus', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('125', 'Daniel', 'Krag Stubbe', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('126', 'Ellen ', 'Jensen', 2010, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('127', 'Flora ', 'Nørregaard Emus', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('128', 'Frey ', 'Egholm Høgh', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('129', 'Ida ', 'Langseth', 2010, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('130', 'Ida ', 'Piper', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('131', 'Isabella ', 'Gauger', 2010, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('132', 'Jakob', 'Bredenfeld Matzen', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('133', 'Jeppe ', 'Borring Andersen', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('134', 'Jonas ', 'Rønholt Malberg', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('135', 'Madicken ', 'Markussen', 2010, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('136', 'Oscar ', 'Kaiser Djørup', 2009, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('137', 'Rasmus ', 'Heilmann', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('138', 'Selma ', 'Steinmann', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('139', 'Siri ', 'Egholm Høgh', 2010, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('140', 'Sofie ', 'Weng Lind-Christensen', 2009, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('141', 'Valdemar ', 'Koldborg', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('142', 'William ', 'Andersen', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('143', 'William ', 'Hoffmann Madsen', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('144', 'Zayyan ', 'Mohammad', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('145', 'August ', 'Bagger Christensen', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('146', 'Gustav ', 'Søndergaard Capaldi', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('147', 'Linus ', 'Nørregaard Emus', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('148', 'Viktor ', 'Knudsen', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('149', 'Camilla', 'Dufour', 1996, 'WOMAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('150', 'Gustav Elvis', 'Capaldi', 2007, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('151', 'Ida Marie', 'Sand', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('153', 'Joakim', 'Brønnum', 1997, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('155', 'Villads', 'Kruse', 2003, 'MAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('156', 'Andreas', 'Moesgaard', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('157', 'Ida', 'Langseth', 2010, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('158', 'Johannes', 'Bredenfeld Matzen', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('159', 'Silja Sofia', 'Linderoth', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('160', 'Ida', 'Svinth Thommesen', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('161', 'Mads', 'Wittrup Hansen', 2008, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('162', 'Frederik', 'Arentoft Rindshøj', 1999, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('163', 'Maise-marie', 'S. Wiid', 2010, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('164', 'Ella', 'Moth Wolffbrandt', 2010, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('165', 'Dagmar', 'Mulipola', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('166', 'Karl', 'Lanng Geneser', 2011, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('167', 'Nicoline', 'Vergo Mariussen', 2011, 'WOMAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('168', 'Isabella', 'Flach', 2008, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('169', 'Ingolf', 'Ougaard', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('170', 'Carl ', 'Haagensen', 2010, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('171', 'Silke', 'Holtz', 2010, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('172', 'Sine', 'Kjeldahl', 2012, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('173', 'Clara', 'Weng Lind-Christensen', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('174', 'Kaya', 'Wismar', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('175', 'Selma', 'Langkjær', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('176', 'Cecilie Philip', 'Beer', 2010, 'WOMAN', 'PARA');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('177', 'Nikolaj', 'Rud', 2010, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('178', 'Noah', 'Helle', 2010, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('179', 'Mille', 'Frydendahl', 2006, 'WOMAN', 'S2');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('180', 'Frederik', 'Lollike', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('181', 'Bror Lauge', 'Gellert', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('182', 'Lauge Meinertz', 'Jakobsen', 2010, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('183', 'Mads', 'Rishøj', 1999, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('184', 'Arthur Dalen', 'Ellegaard', 2001, 'MAN', 'S1');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('185', 'Dagmar', 'Marager', 2011, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('186', 'Oskar ', 'Wæsel', 2010, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('187', 'Bjørk', 'Egholm Høgh', 2012, 'WOMAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('188', 'Victoria', 'Kryshtalova', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('189', 'Raymi Noah', 'Trevino Hansen', 2008, 'MAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('190', 'Anna', 'Pasqale Lind-Christensen', 2012, 'WOMAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('191', 'Harald', 'Rindel-Rasmussen', 2011, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('192', 'Asger', 'Heine Lund', 2011, 'MAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('193', 'Caroline', 'Leander Søltoft', 2010, 'WOMAN', 'S4');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('194', 'Frederik', 'Flach', 2012, 'MAN', '');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('195', 'Max', 'Schou-Sørensen', 2009, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('196', 'Fiona ', 'Schou-Sørensen', 2009, 'WOMAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('197', 'Saga', 'Magnusson', 2011, 'WOMAN', 'Talent');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('198', 'Niklas Hyldekær', 'Janstrup', 2011, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('202', 'Alvin ', 'K. Djørup', 2011, 'MAN', 'S5');
insert into athlete (ref, first_name, last_name, year, gender, team_ref) values ('203', 'Ole', 'Christensen', 2011, 'MAN', 'Talent');
